# Build matrix / environment variable are explained on:
# http://about.travis-ci.org/docs/user/build-configuration/
# This file can be validated on:
# http://lint.travis-ci.org/

sudo: required

dist: trusty

language: cpp

os:
    - linux
    - osx

compiler:
    - gcc
    - clang

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - openssl
            - libssl-dev
            - libcurl4-openssl-dev
            - cmake
            - cmake-data
            - gcc-4.9
            - g++-4.9
            - gfortran-4.9
            - clang-3.7
            #    - valgrind

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
          export FC="gfortran-4.9";
          if [[ "$CXX" == "g++" ]]; then
              export CXX="g++-4.9";
              export CC="gcc-4.9";
          fi;
      elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
          brew update && brew install gcc && brew install libidn && export FC="gfortran";
      fi

install:
    - echo ${PATH}
    - echo ${CC}
    - echo ${CXX}
    - echo ${FC}

before_script:
    - cmake --version
    - curl --version
    - ${CC} --version
    - ${CXX} --version
    - ${FC} --version

script:
    - mkdir build
    - cd build
      #limits screen output
    - cmake .. 2>&1 | grep 'BootsOnTheGround\| TPL'
    - cmake --build .
    - ctest
# enable cache
#cache: ccache
