# Build matrix / environment variable are explained on:
# http://about.travis-ci.org/docs/user/build-configuration/
# This file can be validated on:
# http://lint.travis-ci.org/

sudo: none

dist: trusty

language: cpp

os:
    - linux
    - osx

compiler:
    - gcc
    - clang

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - openssl
            - libssl-dev
            - libcurl4-openssl-dev
            - libblas-dev
            - liblapack-dev
            - cmake
            - cmake-data
            - gcc-4.9
            - g++-4.9
            - gfortran-4.9
            - clang-3.7

install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
          export FC="gfortran-4.9";
          if [[ "$CXX" == "g++" ]]; then
              export CXX="g++-4.9";
              export CC="gcc-4.9";
          fi;
      elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
          travis_wait brew install gcc && brew install libidn && export FC="gfortran";
          brew install ccache;
          export PATH="/usr/local/opt/ccache/libexec:$PATH";
          brew install coreutils;
          export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH";
          rvm get stable --auto-dot-files;
          rvm reset;
      fi
    - echo ${PATH}
    - echo ${CC}
    - echo ${CXX}
    - echo ${FC}
    - cmake --version
    - curl --version
    - ${CC} --version
    - ${CXX} --version
    - ${FC} --version

before_script: |
  function keep_alive() {
    while true; do
      echo -en "\a"
      sleep 5
    done
  }
  keep_alive &


script:
    - mkdir build && cd build
    #the configure needs this line suppression strategy
    - stdbuf -oL cmake .. 2>stderr.log |  grep --line-buffered '\[BootsOnTheGround\]\|\[hunter\]\|%\]'
    - cmake --build .
    - ctest

cache: ccache

